============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/james/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 18 items

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_no_duplicate_users_in_shadow 
-------------------------------- live log setup --------------------------------
2021-11-15 14:53:36 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
2021-11-15 14:53:36 INFO      botocore.credentials:credentials.py:1217 Found credentials in shared credentials file: ~/.aws/credentials
2021-11-15 14:53:36 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
2021-11-15 14:53:47 INFO      integration_testing:clouds.py:132 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
KEYPAIR_NAME=None
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OPENSTACK_NETWORK=falcojr_admin_net
ORACLE_AVAILABILITY_DOMAIN=qIZq:PHX-AD-3
OS_IMAGE=bionic
PLATFORM=ec2
PUBLIC_SSH_KEY=None
RUN_UNSTABLE=False
2021-11-15 14:53:47 INFO      integration_testing:conftest.py:156 Setting up environment for ec2
2021-11-15 14:53:47 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=ami-020db2c14939a8efb
user_data=None
2021-11-15 14:54:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:25 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:26 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:28 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:29 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:30 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:31 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:54:32 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-11-15 14:54:32 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-15 14:54:46 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-15 14:54:46 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:47 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:49 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:50 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:51 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:53 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:55 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:57 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:54:58 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:00 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:01 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:02 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:05 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:08 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:09 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:12 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:13 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:14 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:16 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:17 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:55:17 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-15 14:55:18 INFO      integration_testing:clouds.py:176 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f2053ecf0b8>, instance=ec2.Instance(id='i-01fc2a18747d1b133'))
2021-11-15 14:55:18 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
2021-11-15 14:55:19 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.3-1-g6803368d-0ubuntu1~18.04.4
2021-11-15 14:55:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
2021-11-15 14:55:19 INFO      integration_testing:clouds.py:186 image serial: 20211027
2021-11-15 14:55:19 INFO      integration_testing:instances.py:152 Installing proposed image
2021-11-15 14:55:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2021-11-15 14:55:19 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get update -q'
2021-11-15 14:55:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2021-11-15 14:55:36 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init -v'
2021-11-15 14:55:37 INFO      integration_testing:instances.py:139 Installed cloud-init version: 21.4-0ubuntu1~18.04.1
2021-11-15 14:55:37 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-15 14:55:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-15 14:55:38 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo cloud-init clean --logs'
2021-11-15 14:55:39 INFO      pycloudlib.instance:instance.py:175 executing: sh -c 'sudo rm -rf /var/log/syslog'
2021-11-15 14:58:12 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:58:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:58:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:58:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:58:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:58:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 14:58:18 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-11-15 14:58:19 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-15 14:58:32 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-15 14:58:32 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:33 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:34 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:36 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:37 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:38 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:40 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:41 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:42 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:43 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:44 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:46 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:47 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:48 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:49 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:50 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:52 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:53 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:54 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:55 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:56 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:58 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:58:59 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:00 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:01 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:02 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:03 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:04 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:06 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:07 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:08 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:09 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 14:59:12 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-15 14:59:17 INFO      integration_testing:instances.py:116 Created new image: ami-0b210eef639cb7b55
2021-11-15 15:00:02 INFO      integration_testing:conftest.py:162 Done with environment setup
2021-11-15 15:00:02 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=ami-0b210eef639cb7b55
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
  list:
    - tom:mypassword123!
    - dick:RANDOM
    - harry:RANDOM
    - mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-11-15 15:00:34 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:07 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:08 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:09 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:10 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:11 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:13 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:14 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:15 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:16 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:17 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:18 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:19 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:20 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:22 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:23 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:24 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:01:25 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-11-15 15:01:27 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-15 15:01:41 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-15 15:01:42 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:43 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:44 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:46 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:47 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:48 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:50 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:51 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:53 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:54 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:55 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:56 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:58 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:01:59 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:00 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:02 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:03 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:04 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:05 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:07 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:08 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:09 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:13 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:14 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:16 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:18 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:19 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:20 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:21 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:23 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:24 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:25 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:26 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:28 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:30 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:31 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:33 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:34 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:02:34 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-15 15:02:41 INFO      integration_testing:clouds.py:176 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f2053ecf0b8>, instance=ec2.Instance(id='i-0cf20981d720ea21e'))
2021-11-15 15:02:41 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
2021-11-15 15:02:48 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~18.04.1
2021-11-15 15:02:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
2021-11-15 15:02:48 INFO      integration_testing:clouds.py:186 image serial: 20211027
-------------------------------- live log call ---------------------------------
2021-11-15 15:02:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [  5%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_password_in_users_dict_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:02:48 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:02:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 11%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_password_in_chpasswd_list_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:02:48 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:02:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 16%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:02:48 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:02:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 22%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_not_stored_in_cloud_init_output_log 
-------------------------------- live log setup --------------------------------
2021-11-15 15:02:48 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:02:48 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init-output.log'
PASSED                                                                   [ 27%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_random_passwords_emitted_to_serial_console 
-------------------------------- live log setup --------------------------------
2021-11-15 15:02:49 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
PASSED                                                                   [ 33%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_explicit_password_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:05:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:05:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 38%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_shadow_expected_users 
-------------------------------- live log setup --------------------------------
2021-11-15 15:05:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:05:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 44%]
tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_sshd_config 
-------------------------------- live log setup --------------------------------
2021-11-15 15:05:28 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:05:28 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/sshd_config'
PASSED                                                                   [ 50%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_no_duplicate_users_in_shadow 
-------------------------------- live log setup --------------------------------
2021-11-15 15:06:13 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
2021-11-15 15:06:13 INFO      integration_testing:clouds.py:171 Launching instance with launch_kwargs:
image_id=ami-0b210eef639cb7b55
user_data=#cloud-config
ssh_pwauth: yes
users:
  - default
  - name: tom
    # md5 gotomgo
    passwd: "$1$S7$tT1BEDIYrczeryDQJfdPe0"
    lock_passwd: false
  - name: dick
    # md5 gocubsgo
    passwd: "$1$ssisyfpf$YqvuJLfrrW6Cg/l53Pi1n1"
    lock_passwd: false
  - name: harry
    # sha512 goharrygo
    passwd: "$6$LF$9Z2p6rWK6TNC1DC6393ec0As.18KRAvKDbfsGJEdWN3sRQRwpdfoh37EQ3yUh69tP4GSrGW5XKHxMLiKowJgm/"
    lock_passwd: false
  - name: jane
    # sha256 gojanego
    passwd: "$5$iW$XsxmWCdpwIW8Yhv.Jn/R3uk6A4UaicfW5Xp7C9p9pg."
    lock_passwd: false
  - name: "mikey"
    lock_passwd: false

chpasswd:
    list: |
      tom:mypassword123!
      dick:RANDOM
      harry:RANDOM
      mikey:$5$xZ$B2YGGEx2AOf4PeW48KC6.QyT1W2B4rZ9Qbltudtha89

2021-11-15 15:06:45 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:46 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:47 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:49 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:50 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:51 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:52 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:53 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:54 INFO      pycloudlib.instance:instance.py:175 executing: sh -c whoami
2021-11-15 15:06:55 INFO      paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_7.6p1)
2021-11-15 15:06:55 INFO      paramiko.transport:transport.py:1819 Authentication (publickey) successful!
2021-11-15 15:07:06 INFO      pycloudlib.instance:instance.py:175 executing: which systemctl
2021-11-15 15:07:06 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:08 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:09 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:10 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:11 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:12 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:13 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:15 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:16 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:17 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:18 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:20 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:21 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:22 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:23 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:25 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:26 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:27 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:28 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:29 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:30 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:31 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:33 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:34 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:35 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:36 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:37 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:38 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:39 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:41 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:42 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:43 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:44 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:45 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:46 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:47 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:48 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:50 INFO      pycloudlib.instance:instance.py:175 executing: systemctl is-active cloud-init.target
2021-11-15 15:07:50 INFO      pycloudlib.instance:instance.py:175 executing: cloud-init status --wait --long
2021-11-15 15:07:54 INFO      integration_testing:clouds.py:176 Launched instance: EC2Instance(key_pair=KeyPair(/home/james/.ssh/id_rsa, /home/james/.ssh/id_rsa.pub, name=james), client=<botocore.client.EC2 object at 0x7f2053ecf0b8>, instance=ec2.Instance(id='i-0f62e27c2a8e91198'))
2021-11-15 15:07:54 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cloud-init --version'
2021-11-15 15:07:59 INFO      integration_testing:clouds.py:182 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~18.04.1
2021-11-15 15:07:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
2021-11-15 15:07:59 INFO      integration_testing:clouds.py:186 image serial: 20211027
-------------------------------- live log call ---------------------------------
2021-11-15 15:07:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 55%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_password_in_users_dict_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:07:59 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:07:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 61%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_password_in_chpasswd_list_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:07:59 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:07:59 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 66%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:08:00 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:08:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 72%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_not_stored_in_cloud_init_output_log 
-------------------------------- live log setup --------------------------------
2021-11-15 15:08:00 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:08:00 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /var/log/cloud-init-output.log'
PASSED                                                                   [ 77%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_random_passwords_emitted_to_serial_console 
-------------------------------- live log setup --------------------------------
2021-11-15 15:08:00 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
PASSED                                                                   [ 83%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_explicit_password_set_correctly 
-------------------------------- live log setup --------------------------------
2021-11-15 15:10:39 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:10:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 88%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_shadow_expected_users 
-------------------------------- live log setup --------------------------------
2021-11-15 15:10:39 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:10:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/shadow'
PASSED                                                                   [ 94%]
tests/integration_tests/modules/test_set_password.py::TestPasswordListString::test_sshd_config 
-------------------------------- live log setup --------------------------------
2021-11-15 15:10:39 INFO      integration_testing:clouds.py:91 Detected image: image_id=bionic os=ubuntu release=bionic
-------------------------------- live log call ---------------------------------
2021-11-15 15:10:39 INFO      pycloudlib.instance:instance.py:175 executing: sudo -- sh -c 'cat /etc/ssh/sshd_config'
PASSED                                                                   [100%]
------------------------------ live log teardown -------------------------------
2021-11-15 15:11:10 INFO      integration_testing:clouds.py:207 Deleting snapshot image created for this testrun: ami-0b210eef639cb7b55


=============================== warnings summary ===============================
../envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/_pytest/config/__init__.py:1184: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    _pytest.deprecated.STRICT_OPTION, stacklevel=2

conftest.py:68
  /home/james/cloud-init/conftest.py:68: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(autouse=True)

conftest.py:168
  /home/james/cloud-init/conftest.py:168: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:104
  /home/james/cloud-init/tests/integration_tests/conftest.py:104: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='session')

tests/integration_tests/conftest.py:270
  /home/james/cloud-init/tests/integration_tests/conftest.py:270: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture

tests/integration_tests/conftest.py:277
  /home/james/cloud-init/tests/integration_tests/conftest.py:277: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='module')

tests/integration_tests/conftest.py:284
  /home/james/cloud-init/tests/integration_tests/conftest.py:284: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
  Use @pytest.fixture instead; they are the same.
    @pytest.yield_fixture(scope='class')

tests/integration_tests/modules/test_set_password.py::TestPasswordList::test_no_duplicate_users_in_shadow
  /home/james/envs/cloud-init36/lib/python3.6/site-packages/simplestreams/mirrors/__init__.py:207: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.prefix, path)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 18 passed, 8 warnings in 1054.66s (0:17:34) ==================
